# Generated by Django 2.2.19 on 2021-03-22 10:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Geopolitical_Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geopolitical_zone', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name_plural': 'Geopolitical zones',
            },
        ),
        migrations.CreateModel(
            name='Grade_Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level_name', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name_plural': 'Grade Levels',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name_plural': 'Ranks',
            },
        ),
        migrations.CreateModel(
            name='Salary_Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_structure_name', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name_plural': 'Salary structures',
            },
        ),
        migrations.CreateModel(
            name='State_Of_Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=800)),
                ('LGA', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name_plural': 'States of origin',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name_plural': 'Steps',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=800)),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('date_of_first_appointment', models.DateField(max_length=800)),
                ('phone_no', models.CharField(max_length=800)),
                ('file_no', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('confirmation_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('geopolitical_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Geopolitical_Zone', verbose_name='geopolitical zone')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Grade_Level', verbose_name='grade level')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Rank', verbose_name='rank')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.State_Of_Origin', verbose_name='state of origin')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Step', verbose_name='step')),
            ],
            options={
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=800)),
                ('qualification_date', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Staff', verbose_name='staff')),
            ],
            options={
                'verbose_name_plural': 'qualifications',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateTimeField(auto_now_add=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Grade_Level', verbose_name='grade level')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Staff', verbose_name='staff')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Step', verbose_name='step')),
            ],
            options={
                'verbose_name_plural': 'Steps',
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department', verbose_name='department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Staff', verbose_name='staff')),
            ],
            options={
                'verbose_name_plural': 'Postings',
            },
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.State_Of_Origin', verbose_name='State')),
            ],
            options={
                'verbose_name_plural': 'Local Government Areas',
            },
        ),
    ]
